plugins {
    id 'java'
    id 'war'
    id 'org.springframework.boot' version '3.4.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'eclipse'
}

group = 'com.winter'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-rest'
    implementation 'org.springframework.boot:spring-boot-starter-data-neo4j'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'jakarta.inject:jakarta.inject-api:2.0.1'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.4'
    implementation 'org.springframework.webflow:spring-webflow:3.0.0'
    implementation 'org.apache.velocity:velocity-engine-core:2.4.1'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework:spring-test'
    implementation 'junit:junit:4.13.2'
    implementation 'org.mockito:mockito-core'

    implementation 'org.apache.tomcat.embed:tomcat-embed-jasper' 
    implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api'
    runtimeOnly 'org.glassfish.web:jakarta.servlet.jsp.jstl' 
    
    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly 'com.h2database:h2'
    implementation 'org.springframework.security:spring-security-taglibs'
    
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    
    providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
    
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:3.0.4'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

compileJava {
    exclude 'org/springframework/social/**'
    exclude 'com/spring/cho2/**'
    exclude 'com/springinpratice/**'
    exclude 'com/springinpractice/dao/**'
    exclude 'com/springinpractice/ch02/**'
    exclude 'com/springinpractice/ch05/**'
    exclude 'com/springinpractice/ch09/**'
    exclude 'com/springinpractice/ch10/**'
    exclude 'com/springinpractice/ch11/**'
    exclude 'com/springinpractice/ch12/**'
    exclude 'com/springinpractice/ch13/**'
    exclude 'com/springinpractice/ch14/kite/config/**'
    exclude 'com/springinpractice/ch14/kite/guard/**'
    exclude 'com/springinpractice/ch14/kite/interceptor/**'
    exclude 'com/springinpractice/ch14/kite/AbstantactGuard.java'
    exclude 'com/springinpractice/ch14/kite/sample/service/impl/MessageServiceImpl1.java'
    exclude 'com/springinpractice/ch08/service/impl/ContactServicelmpl.java'
    exclude 'com/winter/word/Account.java'
    exclude 'com/winter/word/AccountDao.java'
    exclude 'com/winter/word/AccountService.java'
    exclude 'com/winter/word/CsvAccountDao.java'
    exclude 'com/winter/word/JdbcAccountDao.java'
}

eclipse {
    wtp {
        facet {
            facet(name: 'jst.web', version: '6.0')
            facet(name: 'jst.java', version: '21') 
        }
    }
}